---
name: CI/CD to Kubernetes

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.IMAGE_REGISTRY_URL }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K8S_CONFIG }}" > ~/.kube/config
          chmod 700 ~/.kube
          chmod 400 ~/.kube/config

      - name: Deploy to Kubernetes
        run: >
          kubectl set image deployment/${{ secrets.K8S_DEPLOYMENT_NAME }}
          ${{ secrets.K8S_DEPLOYMENT_CONTAINER_NAME }}=${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          --namespace=${{ secrets.K8S_NAMESPACE }}
